name: Deploy CI

run-name: Deploy by @${{ github.actor }}

on:
  push:
    branches: ["develop"]
  pull_request:
    branches: ["develop"]

jobs:
  install:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3

      - name: Setup node version
        uses: actions/setup-node@v3
        with:
          node-version: 18
          cache: 'npm'
      
      - name: Cache node modules
        uses: actions/cache@v3
        with:
          path: node_modules
          key: node_modules-${{hashFiles('package-lock.json')}}
          restore-keys: node_modules-
      
      - name: Install dependencies
        run: npm install
  build:
    needs: install
    runs-on: ubuntu-latest
    steps:
      - uses: actions/cache@v3
      - run: npm run clean
      - run: npm run build
      - run: npm run douban
  deploy:
    needs: [install, build]
    runs-on: ubuntu-latest
    steps:
      - uses: actions/cache@v3
      - run: npm run deploy

      